# Generated by Django 3.0.3 on 2020-10-15 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('url', models.TextField()),
                ('urlImagen', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('autor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fuente')),
            ],
        ),
        migrations.AddField(
            model_name='preferencia',
            name='id_noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Noticia'),
        ),
    ]
