# Generated by Django 3.0.3 on 2020-10-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201015_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencia',
            old_name='id_noticia',
            new_name='noticia',
        ),
    ]
