# Generated by Django 3.0.3 on 2020-10-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201015_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencia',
            old_name='noticia',
            new_name='id_noticia',
        ),
    ]
